#! /usr/bin/bash

file_name="$1"

stdout() {
	if [ -n "$1" ]; then
		echo "$1"
	fi
}

rm -rf "$file_name.o"
rm -rf "$file_name.elf"

rm -rf lib/*.o

for file in lib/*.S; do
	file="$(basename "$PWD/lib/$file" .S)"

	echo -n "Compiling 'lib/$file.S'... "

	if output=$(nasm -f elf64 "lib/$file.S" -o "lib/$file.o" 2>&1); then
		echo "OK"
		stdout "$output"
	else
		status="$?"
		echo "ERR"
		stdout "$output"
		exit "$status"
	fi
done

echo -n "Compiling '$file_name.S'... "

if output=$(nasm -f elf64 "$file_name.S" -o "$file_name.o" 2>&1); then
	echo "OK"
	stdout "$output"

	echo -n "Linking '$file_name.o'... "

	if output=$(ld "$file_name.o" ./lib/*.o -o "$file_name.elf" 2>&1); then
		echo "OK"
		stdout "$output"

		chmod +x "$file_name.elf"
	else
		echo "ERR"
		stdout "$output"
	fi
else
	echo "ERR"
	stdout "$output"
fi

rm -rf "$file_name.o"
